name: Unit Test Application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build project
        run: docker-compose build
      - name: Build database
        run: docker-compose run --rm migrate
      - name: Run Unit tests
        run: docker-compose run --rm test